
server:
  port: 8080  # 这是你应用的 HTTP 端口，如果需要可以设置为 8443 等
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # 指定密钥库文件路径
    key-store-password: twitter-2025   # 密钥库密码
    key-store-type: PKCS12            # 密钥库类型
    key-alias: tomcat                # 密钥别名

#server:
#  ssl:
#    key-store: classpath:myssl.p12       # 指定证书路径，"classpath" 表示从项目的资源目录中加载
#    key-store-password: twitter2025    # 证书的密码（即你在创建证书时输入的密码）
#    key-store-type: PKCS12               # 证书存储类型（PKCS12）
#    key-alias: myssl                     # 别名，通常是你在生成证书时指定的别名（如 myssl）
#    key-password: twitter2025          # 密钥的密码，如果和密钥库密码相同，可以不写
#    enabled: true                        # 启用 HTTPS
#  port: 8080


# 打印 SQL 语句
logging:
  level:
#    org.apache.tomcat.util.net: DEBUG
#    org.springframework.boot.web.embedded.tomcat: DEBUG
    com.ganhuoshitang.multipledatasources.mapper: debug

springdoc:
  api-docs:
    enabled: true  # 启用 Swagger 文档
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 访问路径

